'use client'
import { useEffect, useState, useRef } from 'react'
import Sidebar from '@/components/Sidebar'
import { examsApi, studyPlansApi } from '@/lib/api'

const DEMO_EXAMS=[
  {id:'1',course_code:'CS401',course_title:'Algorithms & Data Structures',exam_type:'FINAL',semester:'Spring 2025'},
  {id:'2',course_code:'MATH301',course_title:'Linear Algebra',exam_type:'MIDTERM',semester:'Spring 2025'},
  {id:'3',course_code:'PHYS201',course_title:'Classical Mechanics',exam_type:'FINAL',semester:'Spring 2025'},
]

const DEMO_PLAN=`# Study Plan: CS401 — Algorithms & Data Structures

## Overview
AI-generated plan for your FINAL exam on May 12th. Total preparation time: 18 hours over 2 weeks.

---

## Week 1: Core Foundations

**Day 1–2 · Sorting Algorithms (4h)**
- QuickSort, MergeSort, HeapSort — implement from scratch
- Time complexity proofs for each
- Practice: LeetCode 912, 147, 148

**Day 3–4 · Tree Structures (4h)**
- BST operations: insert, delete, search O(log n)
- AVL rotations and balancing
- Red-Black tree properties

**Day 5–6 · Graph Algorithms (4h)**
- BFS, DFS traversal patterns
- Dijkstra shortest path
- Practice: LeetCode 200, 133, 743

## Week 2: Advanced Topics

**Day 7–9 · Dynamic Programming (6h)**
- Identify optimal substructure
- Memoization vs tabulation
- Classic patterns: knapsack, LCS, coin change

**Day 10–11 · Complexity Analysis (3h)**
- Big-O, Big-Omega, Big-Theta
- Amortized analysis
- Space complexity trade-offs

**Day 12 · Final Review (3h)**
- Mock exam under timed conditions
- Review weak areas only
- Sleep 8h minimum before exam

---

## ⚠ Risk Assessment
- **High risk:** Dynamic Programming (complex, many patterns)
- **Medium risk:** Graph algorithms (implementation details)
- **Lower risk:** Sorting (well-practiced)

*Generated by Claude AI — ExamFlow v2*`

export default function StudyPlansPage(){
  const [exams,setExams]=useState([])
  const [selectedId,setSelectedId]=useState('')
  const [plan,setPlan]=useState('')
  const [streaming,setStreaming]=useState(false)
  const [loading,setLoading]=useState(true)
  const planRef=useRef(null)

  useEffect(()=>{
    examsApi.getAll()
      .then(d=>{const list=d?.exams||d||[];setExams(list);if(list[0])setSelectedId(list[0].id)})
      .catch(()=>{setExams(DEMO_EXAMS);setSelectedId(DEMO_EXAMS[0].id)})
      .finally(()=>setLoading(false))
  },[])

  useEffect(()=>{if(planRef.current)planRef.current.scrollTop=planRef.current.scrollHeight},[plan])

  async function generate(){
    if(!selectedId)return
    setPlan('');setStreaming(true)
    try{
      await studyPlansApi.stream(selectedId,(chunk,full)=>setPlan(full),()=>setStreaming(false))
      return
    }catch{}
    try{
      const d=await studyPlansApi.generate(selectedId)
      const text=d?.study_plan||d?.plan||JSON.stringify(d,null,2)
      let i=0
      const iv=setInterval(()=>{
        if(i>=text.length){clearInterval(iv);setStreaming(false);return}
        setPlan(p=>p+text[i]);i+=5
      },10)
    }catch{
      let i=0
      const iv=setInterval(()=>{
        if(i>=DEMO_PLAN.length){clearInterval(iv);setStreaming(false);return}
        setPlan(p=>p+DEMO_PLAN[i]);i+=6
      },8)
    }
  }

  const sel=exams.find(e=>e.id===selectedId)

  return(
    <div style={{display:'flex',minHeight:'100vh'}}>
      <Sidebar/>
      <main style={{marginLeft:220,flex:1,padding:32,maxWidth:1100}}>
        <div style={{marginBottom:28}}>
          <h1 style={{fontFamily:'Bebas Neue,serif',fontSize:'2.5rem',letterSpacing:'.1em',marginBottom:4}}>STUDY PLANS</h1>
          <p style={{color:'rgba(255,255,255,.4)',fontSize:14}}>AI-generated personalised study schedules, streamed in real time</p>
        </div>

        <div style={{display:'grid',gridTemplateColumns:'280px 1fr',gap:24,alignItems:'start'}}>
          <div style={{display:'flex',flexDirection:'column',gap:14}}>
            <div className="glow-card" style={{padding:22}}>
              <label className="label" style={{marginBottom:10}}>Select Exam</label>
              {loading?<div className="input-dark" style={{height:42,background:'rgba(255,255,255,.05)'}}/>:(
                <select className="input-dark" value={selectedId} onChange={e=>setSelectedId(e.target.value)}>
                  {exams.map(ex=><option key={ex.id} value={ex.id}>{ex.course_code} — {ex.exam_type}</option>)}
                </select>
              )}
              {sel&&(
                <div style={{marginTop:12,padding:12,background:'rgba(255,255,255,.03)',borderRadius:8}}>
                  <p style={{fontSize:12,color:'rgba(255,255,255,.55)',fontWeight:500}}>{sel.course_title}</p>
                  <p style={{fontSize:10,color:'rgba(255,255,255,.25)',marginTop:3,fontFamily:'DM Mono,monospace'}}>{sel.exam_type} · {sel.semester}</p>
                </div>
              )}
              <button className="btn-acid" onClick={generate} disabled={streaming||!selectedId} style={{width:'100%',marginTop:14,display:'flex',alignItems:'center',justifyContent:'center',gap:8}}>
                {streaming?<>⟳ Generating...</>:<>⚡ Generate Plan</>}
              </button>
            </div>

            <div className="glow-card" style={{padding:18}}>
              <p style={{fontSize:12,color:'rgba(255,255,255,.5)',fontWeight:500,marginBottom:10}}>🧠 How it works</p>
              <div style={{fontSize:11,color:'rgba(255,255,255,.3)',lineHeight:1.7}}>
                <p>• Claude AI analyses your exam schedule</p>
                <p>• Builds a day-by-day study timeline</p>
                <p>• Flags high-risk topics for priority</p>
                <p>• Streams response token by token</p>
              </div>
            </div>
          </div>

          <div className="glow-card" style={{padding:24}}>
            <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:16}}>
              <p className="label">Generated Plan</p>
              {streaming&&<span style={{fontSize:10,color:'#c8ff00',fontFamily:'DM Mono,monospace',animation:'pulse 1s infinite'}}>● STREAMING</span>}
            </div>
            {!plan&&!streaming?(
              <div style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',height:480,color:'rgba(255,255,255,.15)'}}>
                <div style={{fontSize:40,marginBottom:12}}>🧠</div>
                <p style={{fontSize:14}}>Select an exam and click Generate</p>
              </div>
            ):(
              <div ref={planRef} style={{height:480,overflowY:'auto',fontSize:13,color:'rgba(255,255,255,.75)',lineHeight:1.8,whiteSpace:'pre-wrap',fontFamily:'DM Sans,sans-serif'}}>
                {plan}{streaming&&<span className="streaming-cursor"/>}
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
