'use client'
import { useEffect, useRef, useState } from 'react'
import { examsApi, studyPlansApi } from '@/lib/api'
import type { Exam } from '@/lib/types'
import { Card, Spinner, ErrorBanner } from '@/components/ui'

const DEMO_CODES = ['CS401', 'MATH301', 'PHYS201']
const DEMO_PLAN = `# Study Plan — Spring 2025

## Executive Summary
Based on your 3 exams with 11 total credit hours, I recommend 18–22 study hours per week over the next 4 weeks.

---

## Week 1: Foundations (Days 1–7)

### CS401 — Algorithms & Data Structures
- **Day 1–2** Sorting algorithms (QuickSort, MergeSort, HeapSort) — 3h each
- **Day 3** Trees and graphs: BST, AVL, BFS/DFS — 2.5h
- **Day 4** Dynamic programming fundamentals — 3h

### MATH301 — Linear Algebra
- **Day 5** Vector spaces, linear transformations — 2h
- **Day 6** Eigenvalues and eigenvectors — 2.5h

---

## Week 2: Deep Practice (Days 8–14)

### PHYS201 — Classical Mechanics
- **Day 8–9** Newton's laws, kinematics review — 2h/day
- **Day 10** Lagrangian mechanics — 2.5h

### CS401 Continued
- **Day 11** Graph algorithms: Dijkstra, Bellman-Ford — 2h
- **Day 12** NP-completeness and reductions — 2h
- **Day 13** Problem set: 10 LeetCode medium/hard — 3h

---

## Week 3: Integration (Days 15–20)

- Mock exams under timed conditions
- Review weak areas identified in Week 2
- Focus: MATH301 proofs (historically challenging)

---

## Week 4: Final Review (Days 21–24)

- **Day 21** CS401 full review — 4h
- **Day 22** MATH301 formula sheet + past papers — 3h
- **Day 23** PHYS201 problem sets — 3h
- **Day 24** Light review only. Sleep 8+ hours.

---

## ⚠ Risk Assessment

| Subject | Risk | Reason |
|---|---|---|
| CS401 | HIGH | Complex algorithms, many edge cases |
| MATH301 | MEDIUM | Proof-heavy, abstract concepts |
| PHYS201 | LOW | Strong prerequisite coverage |

---

*Generated by Claude AI — ExamFlow v2*`

export default function StudyPlansPage() {
  const [exams, setExams] = useState<Exam[]>([])
  const [codes, setCodes] = useState<string[]>([])
  const [semester, setSemester] = useState('Spring 2025')
  const [dailyHours, setDailyHours] = useState(6)
  const [plan, setPlan] = useState('')
  const [streaming, setStreaming] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [loadingExams, setLoadingExams] = useState(true)
  const planRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    examsApi.list()
      .then(({ exams: list }) => {
        setExams(list)
        setCodes(list.map(e => e.course_code))
      })
      .catch(() => {
        const demoExams: Exam[] = DEMO_CODES.map((c, i) => ({
          id: String(i), course_code: c, course_title: c, exam_type: 'FINAL' as const,
          start_time: '2025-05-12T09:00:00Z', end_time: '2025-05-12T11:00:00Z', semester: 'Spring 2025'
        }))
        setExams(demoExams)
        setCodes(DEMO_CODES)
      })
      .finally(() => setLoadingExams(false))
  }, [])

  useEffect(() => {
    if (planRef.current) planRef.current.scrollTop = planRef.current.scrollHeight
  }, [plan])

  function toggleCode(code: string) {
    setCodes(prev => prev.includes(code) ? prev.filter(c => c !== code) : [...prev, code])
  }

  async function generate() {
    if (codes.length === 0) { setError('Select at least one course'); return }
    setPlan(''); setStreaming(true); setError(null)

    await studyPlansApi.stream(
      { codes, semester, dailyHours, stream: true },
      (_chunk, full) => setPlan(full),
      () => setStreaming(false),
      async (streamErr) => {
        // Fallback: non-streaming
        try {
          const res = await studyPlansApi.generate({ codes, semester, dailyHours })
          const text = res.study_plan || res.plan || JSON.stringify(res, null, 2)
          // Simulate streaming
          let i = 0
          const iv = setInterval(() => {
            if (i >= text.length) { clearInterval(iv); setStreaming(false); return }
            setPlan(text.slice(0, i += 8))
          }, 12)
        } catch {
          // Ultimate fallback: demo
          let i = 0
          const iv = setInterval(() => {
            if (i >= DEMO_PLAN.length) { clearInterval(iv); setStreaming(false); return }
            setPlan(DEMO_PLAN.slice(0, i += 6))
          }, 10)
        }
      }
    )
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-slide-up">
      <div>
        <h1 className="text-2xl font-bold text-surface-900">Study Plans</h1>
        <p className="text-sm text-surface-500 mt-0.5">AI-generated personalised study schedules with real-time streaming</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Controls */}
        <div className="space-y-4">
          <Card>
            <h2 className="text-sm font-semibold text-surface-900 mb-3">Select Courses</h2>
            {loadingExams ? (
              <div className="space-y-2">
                {[1,2,3].map(i => <div key={i} className="skeleton h-8 rounded" />)}
              </div>
            ) : (
              <div className="space-y-2">
                {exams.map(exam => (
                  <label key={exam.id} className="flex items-center gap-2.5 cursor-pointer group">
                    <input
                      type="checkbox"
                      checked={codes.includes(exam.course_code)}
                      onChange={() => toggleCode(exam.course_code)}
                      className="w-4 h-4 rounded border-surface-300 text-brand-600 focus:ring-brand-500"
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-mono text-surface-500">{exam.course_code}</p>
                      <p className="text-xs text-surface-700 truncate">{exam.course_title}</p>
                    </div>
                  </label>
                ))}
              </div>
            )}
          </Card>

          <Card>
            <h2 className="text-sm font-semibold text-surface-900 mb-3">Settings</h2>
            <div className="space-y-3">
              <div>
                <label className="label">Semester</label>
                <input className="input" value={semester} onChange={e => setSemester(e.target.value)} />
              </div>
              <div>
                <label className="label">Daily Study Hours: {dailyHours}h</label>
                <input type="range" min={2} max={12} value={dailyHours}
                  onChange={e => setDailyHours(Number(e.target.value))}
                  className="w-full accent-brand-600" />
                <div className="flex justify-between text-[10px] text-surface-400 mt-0.5">
                  <span>2h</span><span>12h</span>
                </div>
              </div>
            </div>
          </Card>

          {error && <ErrorBanner message={error} />}

          <button onClick={generate} disabled={streaming} className="btn-primary w-full">
            {streaming ? <><Spinner /> Generating...</> : '🧠 Generate Plan'}
          </button>

          <Card className="bg-surface-50 border-surface-100">
            <p className="text-xs font-semibold text-surface-600 mb-2">How it works</p>
            <ul className="text-xs text-surface-500 space-y-1">
              <li>• Claude AI analyses your exam schedule</li>
              <li>• Builds a day-by-day study timeline</li>
              <li>• Flags high-risk subjects</li>
              <li>• Streams response in real time</li>
            </ul>
          </Card>
        </div>

        {/* Output */}
        <Card className="lg:col-span-2 p-0 overflow-hidden">
          <div className="flex items-center justify-between p-4 border-b border-surface-100">
            <h2 className="text-sm font-semibold text-surface-900">Generated Plan</h2>
            {streaming && (
              <span className="inline-flex items-center gap-1.5 text-xs text-brand-600 font-medium">
                <span className="w-1.5 h-1.5 bg-brand-500 rounded-full animate-pulse" />
                Streaming...
              </span>
            )}
            {plan && !streaming && (
              <button
                onClick={() => { const b = new Blob([plan], {type:'text/plain'}); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href=u; a.download='study-plan.md'; a.click() }}
                className="btn-secondary text-xs py-1 px-2.5"
              >
                ↓ Download
              </button>
            )}
          </div>

          {!plan && !streaming ? (
            <div className="flex flex-col items-center justify-center h-96 text-surface-300">
              <span className="text-5xl mb-4">🧠</span>
              <p className="text-sm font-medium text-surface-400">Select courses and generate your plan</p>
            </div>
          ) : (
            <div
              ref={planRef}
              className="p-5 h-[520px] overflow-y-auto streaming-text text-surface-700 whitespace-pre-wrap"
            >
              {plan}
              {streaming && <span className="cursor-blink">|</span>}
            </div>
          )}
        </Card>
      </div>
    </div>
  )
}
